version: '3'

services:
  frontend:
    build: ./streamer-site-frontend
    volumes: 
      - frontend:/volume/dist
  backend:
    build: ./tsquery_rs
    restart: always
    environment:
      - TS_HOST=${TS_HOST}
      - TS_USERNAME=${TS_USERNAME}
      - TS_PASSWORD=${TS_PASSWORD}
    expose: 
      - 3000
    networks:
      - default

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - frontend:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - backend
      - frontend
    networks:
      - nginx-proxy
      - default

volumes:
  frontend:

networks:
  nginx-proxy:
    external: 
      name: nginx-proxy
