[package]
name = "tsquery_rs"
version = "0.1.0"
authors = ["shneky <shneky@protonmail.com>"]
edition = "2018"

[dependencies]
telnet = "0.1.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
actix-web = "1.0.0-beta.4"